<?php

declare(strict_types=1);

namespace SharedKernel\Domain;

enum Currency: string
{
    use EnumTrait;

    case AED = 'UAE Dirham';
    case AFN = 'Afghani';
    case ALL = 'Lek';
    case AMD = 'Armenian Dram';
    case ANG = 'Netherlands Antillean Guilder';
    case AOA = 'Kwanza';
    case ARS = 'Argentine Peso';
    case AUD = 'Australian Dollar';
    case AWG = 'Aruban Florin';
    case AZN = 'Azerbaijan Manat';
    case BAM = 'Convertible Mark';
    case BBD = 'Barbados Dollar';
    case BDT = 'Taka';
    case BGN = 'Bulgarian Lev';
    case BHD = 'Bahraini Dinar';
    case BIF = 'Burundi Franc';
    case BMD = 'Bermudian Dollar';
    case BND = 'BruneisDollar';
    case BOB = 'Boliviano';
    case BOV = 'Mvdol';
    case BRL = 'Brazilian Real';
    case BSD = 'Bahamian Dollar';
    case BTN = 'Ngultrum';
    case BWP = 'Pula';
    case BYN = 'Belarusian Ruble';
    case BZD = 'Belize Dollar';
    case CAD = 'Canadian Dollar';
    case CDF = 'Congolese Franc';
    case CHE = 'WIR Euro';
    case CHF = 'Swiss Franc';
    case CHW = 'WIR Franc';
    case CLF = 'Unidad de Fomento';
    case CLP = 'Chilean Peso';
    case CNY = 'Yuan Renminbi';
    case COP = 'Colombian Peso';
    case COU = 'Unidad de Valor Real';
    case CRC = 'Costa Rican Colon';
    case CUC = 'Peso Convertible';
    case CUP = 'Cuban Peso';
    case CVE = 'Cabo Verde Escudo';
    case CZK = 'Czech Koruna';
    case DJF = 'Djibouti Franc';
    case DKK = 'Danish Krone';
    case DOP = 'Dominican Peso';
    case DZD = 'Algerian Dinar';
    case EGP = 'Egyptian Pound';
    case ERN = 'Nakfa';
    case ETB = 'Ethiopian Birr';
    case EUR = 'Euro';
    case FJD = 'Fiji Dollar';
    case FKP = 'Falkland Islands Pound';
    case GBP = 'Pound Sterling';
    case GEL = 'Lari';
    case GHS = 'Ghana Cedi';
    case GIP = 'Gibraltar Pound';
    case GMD = 'Dalasi';
    case GNF = 'Guinean Franc';
    case GTQ = 'Quetzal';
    case GYD = 'Guyana Dollar';
    case HKD = 'Hong Kong Dollar';
    case HNL = 'Lempira';
    case HTG = 'Gourde';
    case HUF = 'Forint';
    case IDR = 'Rupiah';
    case ILS = 'New Israeli Sheqel';
    case INR = 'Indian Rupee';
    case IQD = 'Iraqi Dinar';
    case IRR = 'Iranian Rial';
    case ISK = 'Iceland Krona';
    case JMD = 'Jamaican Dollar';
    case JOD = 'Jordanian Dinar';
    case JPY = 'Yen';
    case KES = 'Kenyan Shilling';
    case KGS = 'Som';
    case KHR = 'Riel';
    case KMF = 'Comorian Franc';
    case KPW = 'North Korean Won';
    case KRW = 'Won';
    case KWD = 'Kuwaiti Dinar';
    case KYD = 'Cayman Islands Dollar';
    case KZT = 'Tenge';
    case LAK = 'Lao Kip';
    case LBP = 'Lebanese Pound';
    case LKR = 'Sri Lanka Rupee';
    case LRD = 'Liberian Dollar';
    case LSL = 'Loti';
    case LYD = 'Libyan Dinar';
    case MAD = 'Moroccan Dirham';
    case MDL = 'Moldovan Leu';
    case MGA = 'Malagasy Ariary';
    case MKD = 'Denar';
    case MMK = 'Kyat';
    case MNT = 'Tugrik';
    case MOP = 'Pataca';
    case MRU = 'Ouguiya';
    case MUR = 'Mauritius Rupee';
    case MVR = 'Rufiyaa';
    case MWK = 'Malawi Kwacha';
    case MXN = 'Mexican Peso';
    case MXV = 'Mexican Unidad de Inversion UDI';
    case MYR = 'Malaysian Ringgit';
    case MZN = 'Mozambique Metical';
    case NAD = 'Namibia Dollar';
    case NGN = 'Naira';
    case NIO = 'Cordoba Oro';
    case NOK = 'Norwegian Krone';
    case NPR = 'Nepalese Rupee';
    case NZD = 'New Zealand Dollar';
    case OMR = 'Rial Omani';
    case PAB = 'Balboa';
    case PEN = 'Sol';
    case PGK = 'Kina';
    case PHP = 'Philippine Peso';
    case PKR = 'Pakistan Rupee';
    case PLN = 'Zloty';
    case PYG = 'Guarani';
    case QAR = 'Qatari Rial';
    case RON = 'Romanian Leu';
    case RSD = 'Serbian Dinar';
    case RUB = 'Russian Ruble';
    case RWF = 'Rwanda Franc';
    case SAR = 'Saudi Riyal';
    case SBD = 'Solomon Islands Dollar';
    case SCR = 'Seychelles Rupee';
    case SDG = 'Sudanese Pound';
    case SEK = 'Swedish Krona';
    case SGD = 'Singapore Dollar';
    case SHP = 'Saint Helena Pound';
    case SLE = 'Leone';
    case SOS = 'Somali Shilling';
    case SRD = 'Surinam Dollar';
    case SSP = 'South Sudanese Pound';
    case STN = 'Dobra';
    case SVC = 'El Salvador Colon';
    case SYP = 'Syrian Pound';
    case SZL = 'Lilangeni';
    case TGP = 'Pa anga';
    case THB = 'Baht';
    case TJS = 'Somoni';
    case TMT = 'Turkmenistan New Manat';
    case TND = 'Tunisian Dinar';
    case TRY = 'Turkish Lira';
    case TTD = 'Trinidad and Tobago Dollar';
    case TWD = 'New Taiwan Dollar';
    case TZS = 'Tanzanian Shilling';
    case UAH = 'Hryvnia';
    case UGX = 'Uganda Shilling';
    case USD = 'US Dollar';
    case UYI = 'Uruguay Peso en Unidades Indexadas UI';
    case UYU = 'Peso Uruguayo';
    case UYW = 'Unidad Previsional';
    case UZS = 'Uzbekistan Sum';
    case VED = 'Bolivar Soberano';
    case VES = 'Bolivar Soberano Old';
    case VND = 'Dong';
    case VUV = 'Vatu';
    case WST = 'Tala';
    case XAF = 'CFA Franc BEAC';
    case XCD = 'East Caribbean Dollar';
    case XOF = 'CFA Franc BCEAO';
    case XPF = 'CFP Franc';
    case XSU = 'Sucre';
    case YER = 'Yemeni Rial';
    case ZAR = 'Rand';
    case ZMW = 'Zambian Kwacha';
    case ZWL = 'Zimbabwe Dollar';

    /**
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    public function fraction(): int
    {
        return match ($this) {
            self::AED => 2,
            self::AFN => 2,
            self::ALL => 2,
            self::AMD => 2,
            self::ANG => 2,
            self::AOA => 2,
            self::ARS => 2,
            self::AUD => 2,
            self::AWG => 2,
            self::AZN => 2,
            self::BAM => 2,
            self::BBD => 2,
            self::BDT => 2,
            self::BGN => 2,
            self::BHD => 3,
            self::BIF => 0,
            self::BMD => 2,
            self::BND => 2,
            self::BOB => 2,
            self::BOV => 2,
            self::BRL => 2,
            self::BSD => 2,
            self::BTN => 2,
            self::BWP => 2,
            self::BYN => 2,
            self::BZD => 2,
            self::CAD => 2,
            self::CDF => 2,
            self::CHE => 2,
            self::CHF => 2,
            self::CHW => 2,
            self::CLF => 4,
            self::CLP => 0,
            self::CNY => 2,
            self::COP => 2,
            self::COU => 2,
            self::CRC => 2,
            self::CUC => 2,
            self::CUP => 2,
            self::CVE => 2,
            self::CZK => 2,
            self::DJF => 0,
            self::DKK => 2,
            self::DOP => 2,
            self::DZD => 2,
            self::EGP => 2,
            self::ERN => 2,
            self::ETB => 2,
            self::EUR => 2,
            self::FJD => 2,
            self::FKP => 2,
            self::GBP => 2,
            self::GEL => 2,
            self::GHS => 2,
            self::GIP => 2,
            self::GMD => 2,
            self::GNF => 0,
            self::GTQ => 2,
            self::GYD => 2,
            self::HKD => 2,
            self::HNL => 2,
            self::HTG => 2,
            self::HUF => 2,
            self::IDR => 2,
            self::ILS => 2,
            self::INR => 2,
            self::IQD => 3,
            self::IRR => 2,
            self::ISK => 0,
            self::JMD => 2,
            self::JOD => 3,
            self::JPY => 0,
            self::KES => 2,
            self::KGS => 2,
            self::KHR => 2,
            self::KMF => 0,
            self::KPW => 2,
            self::KRW => 0,
            self::KWD => 3,
            self::KYD => 2,
            self::KZT => 2,
            self::LAK => 2,
            self::LBP => 2,
            self::LKR => 2,
            self::LRD => 2,
            self::LSL => 2,
            self::LYD => 3,
            self::MAD => 2,
            self::MDL => 2,
            self::MGA => 2,
            self::MKD => 2,
            self::MMK => 2,
            self::MNT => 2,
            self::MOP => 2,
            self::MRU => 2,
            self::MUR => 2,
            self::MVR => 2,
            self::MWK => 2,
            self::MXN => 2,
            self::MXV => 2,
            self::MYR => 2,
            self::MZN => 2,
            self::NAD => 2,
            self::NGN => 2,
            self::NIO => 2,
            self::NOK => 2,
            self::NPR => 2,
            self::NZD => 2,
            self::OMR => 3,
            self::PAB => 2,
            self::PEN => 2,
            self::PGK => 2,
            self::PHP => 2,
            self::PKR => 2,
            self::PLN => 2,
            self::PYG => 0,
            self::QAR => 2,
            self::RON => 2,
            self::RSD => 2,
            self::RUB => 2,
            self::RWF => 0,
            self::SAR => 2,
            self::SBD => 2,
            self::SCR => 2,
            self::SDG => 2,
            self::SEK => 2,
            self::SGD => 2,
            self::SHP => 2,
            self::SLE => 2,
            self::SOS => 2,
            self::SRD => 2,
            self::SSP => 2,
            self::STN => 2,
            self::SVC => 2,
            self::SYP => 2,
            self::SZL => 2,
            self::TGP => 2,
            self::THB => 2,
            self::TJS => 2,
            self::TMT => 2,
            self::TND => 3,
            self::TRY => 2,
            self::TTD => 2,
            self::TWD => 2,
            self::TZS => 2,
            self::UAH => 2,
            self::UGX => 0,
            self::USD => 2,
            self::UYI => 0,
            self::UYU => 2,
            self::UYW => 4,
            self::UZS => 2,
            self::VED => 2,
            self::VES => 2,
            self::VND => 0,
            self::VUV => 0,
            self::WST => 2,
            self::XAF => 0,
            self::XCD => 2,
            self::XOF => 0,
            self::XPF => 0,
            self::YER => 2,
            self::ZAR => 2,
            self::ZMW => 2,
            self::ZWL => 2,
            default => 0,
        };
    }
}
