version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine3.17
    container_name: ${PROJECT_NAME}_nginx
    restart: on-failure
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ./nginx/dev.conf:/etc/nginx/nginx.conf
    ports:
      - "${HTTP_PORT}:80"
    depends_on:
      - php

  php:
    build:
      context: php
    container_name: ${PROJECT_NAME}_php
    restart: on-failure
    working_dir: /var/www
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - ../:/var/www
      - ./php/dev.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.17-alpine
    container_name: ${PROJECT_NAME}_postgres
    restart: on-failure
    environment:
      - POSTGRES_DB=skeleton
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2-alpine
    container_name: ${PROJECT_NAME}_redis
    restart: on-failure
