name: Common part of the build
description: Common part of the build for the PHP project
inputs:
    COMPOSER_CACHE:
        description: 'Cache for composer'
        required: true
    SYMFONY_CACHE:
        description: 'Cache for composer'
        required: true
runs:
    using: "composite"
    steps:
        -   name: Set up PHP
            uses: shivammathur/setup-php@v2
            with:
                php-version: '8.3'
                coverage: none

        -   name: Load .env.ci
            uses: falti/dotenv-action@v1.1.3
            with:
                path: .env.ci
                export-variables: true
                keys-case: bypass

        -   name: Cache composer dependencies
            uses: actions/cache@v4
            with:
                path: vendor
                key: ${{ inputs.COMPOSER_CACHE }}

        -   name: Cache symfony
            uses: actions/cache@v4
            with:
                path: var/cache
                key: ${{ inputs.SYMFONY_CACHE }}
