name: Common part of the build
description: Common part of the build with database for the PHP project
inputs:
    COMPOSER_CACHE:
        description: 'Cache for composer'
        required: true
    SYMFONY_CACHE:
        description: 'Cache for symfony'
        required: true
runs:
    using: "composite"
    steps:
        -   name: Common setup
            uses: ./.github/actions/common
            with:
                COMPOSER_CACHE: ${{ hashFiles('**/composer.lock') }}
                SYMFONY_CACHE: ${{ github.run_id }}
        -   name: Setup project
            shell: bash
            run: composer migrations:migrate
