name: Code coverage

on:
    workflow_dispatch:
        branches:
            - master

jobs:
    coverage:
        name: Check code coverage
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_DB: skeleton_test
                    POSTGRES_USER: user
                    POSTGRES_PASSWORD: password
                options: >-
                    --health-cmd pg_isready
                    --health-interval 2s
                    --health-timeout 3s
                    --health-retries 10
                ports:
                    - 5432:5432
        steps:
            -   name: Checkout branch
                uses: actions/checkout@v4

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.4'
                    coverage: xdebug

            -   name: Load .env.ci
                uses: falti/dotenv-action@v1.1.3
                with:
                    path: .env.ci
                    export-variables: true
                    keys-case: bypass

            -   name: Build project
                run: |
                    composer install --optimize-autoloader --no-scripts --no-progress --quiet
                    bin/console cache:warmup
                    composer test:database:init

            -   name: Generate coverage report
                run: composer test:coverage

            -   name: Make code coverage badge
                uses: timkrase/phpunit-coverage-badge@v1.2.1
                with:
                    report: var/coverage/index.html
                    report_type: html
                    coverage_badge_path: ./.github/coverage.svg
                    push_badge: true
                    repo_token: ${{ secrets.GITHUB_TOKEN }}
                    commit_message: '[ SKIP-CI ] Update code coverage'
